sudo: required
language: cpp
services: docker
before_install:
  - docker build -t pyorbit .
script:
  - docker run pyorbit  bash -c "source setupEnvironment.sh; cd examples/AccLattice_Tests; ./START.sh lattice_test.py 2"
  
